Ev3ColorLeft:
  type: h4r_ev3_control/Ev3ColorController
  frame_id: color_link_left
  topic_name: /color_left
  publish_rate: 10
  port: in4
  mode: rgb_raw

Ev3ColorRight:
  type: h4r_ev3_control/Ev3ColorController
  frame_id: color_link_right
  topic_name: /color_right
  publish_rate: 10
  port: in3
  mode: rgb_raw

  #Mode:
# rgb_raw
# color
  #0   none
  #1   black
  #2   blue
  #3   green
  #4   yellow
  #5   red
  #6   white
  #7   brown
# ambient
# reflect
